# Generated by Django 3.1.2 on 2020-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police',
            field=models.IntegerField(default=0),
        ),
    ]
